Feature/7
Chomolungma-229/intern-book-app pull request #18
Opened 2022-04-08 08:33 UTC by SuraNSK

## Checklist for Developer
- [x] 最新のdevelopブランチをPullした。Pulled the latest develop branch.
  - できない理由 Reason not to do: 
- [x] Pull RequestをIssueに紐付けた。Connected with the issue.
- [x] 自分をAssignした。Assigned yourself.
- [x] レビュワーを指定した。Assigned reviewer.

## 📝 そのほかの関連するIssue / Related issues other than connected one

- #0
- #0

## ⛏ 変更内容 / Details of Changes

- card,input,textareaを使ってpageを編集して<router-outlet>で表示した。

## 📸 スクリーンショット / Screenshots

<img width="1440" alt="スクリーンショット 2022-04-08 17 07 22" src="https://user-images.githubusercontent.com/87349191/162393358-f0ec6c26-b8ca-4d5c-a411-f8c749bb751e.png">

## レビューするポイント (Points for review):

 - ng serve で開いた時に /pages に行く
 - 見本と大体同じであるかどうか

2022-04-11 01:28 UTC, kusanoshunsuke commented
@SuraNSK 
入力フォームのところいいね！！
下に追加のボタンと入力フォームの下に書籍の情報のcardがあるとより見本に近くなると思うんで追加してみてください〜

2022-04-11 01:46 UTC, SuraNSK commented
わかりました！
追加しておきます！

2022-04-12 06:50 UTC, SuraNSK commented
<img width="1440" alt="スクリーンショット 2022-04-12 15 49 20" src="https://user-images.githubusercontent.com/87349191/162898229-6fe82883-9e3a-424b-9bb3-f4d77eae9805.png">

ボタンとカード追加しました！

2022-04-14 07:51 UTC, hikaru-nakamura-thedott requested changes
いくつか修正点ありましたので、対応お願いします〜

2022-04-14 07:51 UTC, hikaru-nakamura-thedott commented on intern-book-app/src/app/pages/list/list.component.html
> +<img src="https://drive.google.com/uc?id=1RPpbzbHpE_3ScOIez5IWsBfF-flRkyG0" width="800">
「開発がしやすいように入れているテストコード」はコミットには含めない方がいいかな。
今回は画像なのでいつでも気づけそうだし、後で削除することも容易だと思うけど、こういう習慣がついてしまうとconsole.logとかも一緒にコミットしちゃう癖がつくので、今のうちに「機能に関係のないコードがないかコミット前にチェックする」習慣をつけておきましょう！
（偉そうなこと言ってるけど、僕もやってしまう...お互い気をつけましょ）

2022-04-14 07:51 UTC, hikaru-nakamura-thedott commented on intern-book-app/src/app/pages/list/list.component.html
> +            <div class="button">
ボタンを右寄せしたいんですよね？
[materialの例](https://material.angular.io/components/card/examples)にもっと簡単に綺麗に書く方法あるんで、こっち使いましょう。
一番上の例の `mat-card-actions` ってとこを見るいいでしょう。
こういうものは積極的に使っていきましょう！そうすると、以下のことは考えなくて良くなります。

> HTMLにも<button>というタグがあるので、"button"というclass名は良くない。
以下のように考えて命名してあげた方が良いでしょう。
> - ボタンを内包するための領域やコンテナ
    - button-container
    - button-wrapper
    - button-box
> - 中身を右寄せする領域やコンテナ
    - float-right-container
    - float-right-wrapper
    - float-right-box

2022-04-14 07:51 UTC, hikaru-nakamura-thedott commented on intern-book-app/src/app/pages/list/list.component.html
> +            <button mat-raised-button color="warn">削除</button>
インデント一個下げましょう！

2022-04-14 07:51 UTC, hikaru-nakamura-thedott commented on intern-book-app/src/app/pages/list/list.component.html
> +        </div>
長文が入った場合に改行がされるようにしましょう！
モック用のデータだからと言って手を抜かないようにしましょうね！
<img width="1666" alt="スクリーンショット 2022-04-14 16 35 39" src="https://user-images.githubusercontent.com/86763776/163336869-ef0ef1ef-32a0-4157-b4cd-d1b84aa5b2fd.png">

2022-04-14 07:51 UTC, hikaru-nakamura-thedott commented on intern-book-app/src/app/pages/list/list.component.css
> +.mid-width {
"min-width"というクラス名は...というのはbuttonのところでしたので割愛。
あと、"min-width"というクラスでmax-widthプロパティも指定すると名前を超過する機能が積まれているので良くないですねー
CSSの命名規則についてググるといいでしょうー

2022-04-14 07:51 UTC, hikaru-nakamura-thedott commented on intern-book-app/src/app/components/toolbar/toolbar.component.html
> +    <span>書籍登録</span>
ここは「読んだ本」にしましょう〜

2022-04-14 07:51 UTC, hikaru-nakamura-thedott commented on intern-book-app/src/app/components/toolbar/toolbar.component.html
> +    </button>
ここも≡じゃなくて「一覧」にしとこうか〜

2022-04-15 05:50 UTC, hikaru-nakamura-thedott approved these changes
全部直してくれてありがとう！
マージしちゃいますね〜

2022-04-15 05:50 UTC, hikaru-nakamura-thedott commented on intern-book-app/src/app/pages/list/list.component.html
> +        <mat-card-content class="text-wrap">
いいですね！
ひと目で「文字列が入る要素であること」「文字列が改行をすること」がわかる良いクラス名だと思います！

2022-04-15 05:50 UTC, merged